### PR TITLE
Configurable fallback locale

### PR DESCRIPTION
**Pull request by sebinemeth**
Hi, I implemented the configurable fallback locale proposed in PR https://github.com/wojtekmaj/get-user-locale/pull/6. In addition, fallback behavior can be disabled.

### CODE REVIEW

**Comment by sebinemeth** [comment]
Hi, 
Any news on this one? 
Thanks!

**Comment by danielztolnai** [comment]
Hi @wojtekmaj, sorry to bother you, but is there any chance to get this merged?

**Comment by gazben** [comment]
@wojtekmaj I've rebased the changes to the current `main` and resolved the conflicts. Can you take a look?

**Comment by wojtekmaj** [comment]
I couldn't edit this branch so I worked on this a bit more and merged it as 447b295, while adding you both as co-authors. Thank you for your contribution!

**Comment by gazben** [comment]
@wojtekmaj Can you create a new release to npm? Also I guess this can be closed: https://github.com/wojtekmaj/get-user-locale/pull/6

**Pull request closed without merging**
